name: SonarCloud

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pull-requests: write   # allows PR decoration from SonarCloud

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Test (with coverage)
        run: npm test -- --coverage
        env:
          CI: true

      - name: Verify coverage file exists
        run: |
          ls -la
          ls -la coverage || true
          test -f coverage/lcov.info

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    # auto-provided by GitHub
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}      # your SonarCloud token
        with:
          args: >
            -Dsonar.organization=rostyslav-vitech-pipeline
            -Dsonar.projectKey=rostyslav-vitech_github-pipelines
            -Dsonar.sources=src
            -Dsonar.tests=tests
            -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info
